apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-test-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mengshushu-97/agent-test.git
    targetRevision: main
    path: k8s/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-test-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mengshushu-97/agent-test.git
    targetRevision: main
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
